[2022-06-15 16:56:19,621] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.third_task manual__2022-06-15T16:56:17.709983+00:00 [queued]>
[2022-06-15 16:56:19,646] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: our_first_dag_v5.third_task manual__2022-06-15T16:56:17.709983+00:00 [queued]>
[2022-06-15 16:56:19,648] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 16:56:19,648] {taskinstance.py:1357} INFO - Starting attempt 1 of 6
[2022-06-15 16:56:19,649] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-15 16:56:19,681] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): third_task> on 2022-06-15 16:56:17.709983+00:00
[2022-06-15 16:56:19,700] {standard_task_runner.py:52} INFO - Started process 3069 to run task
[2022-06-15 16:56:19,705] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'third_task', 'manual__2022-06-15T16:56:17.709983+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp0d4dxebn', '--error-file', '/tmp/tmpg27qg2lp']
[2022-06-15 16:56:19,709] {standard_task_runner.py:80} INFO - Job 12: Subtask third_task
[2022-06-15 16:56:19,876] {task_command.py:370} INFO - Running <TaskInstance: our_first_dag_v5.third_task manual__2022-06-15T16:56:17.709983+00:00 [running]> on host e2977833d61b
[2022-06-15 16:56:20,034] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=phersonj
AIRFLOW_CTX_DAG_ID=our_first_dag_v5
AIRFLOW_CTX_TASK_ID=third_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-15T16:56:17.709983+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-15T16:56:17.709983+00:00
[2022-06-15 16:56:20,038] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-15 16:56:20,041] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hey, I am task 3, and will be running after task 1 at the same time as task 2']
[2022-06-15 16:56:20,060] {subprocess.py:85} INFO - Output:
[2022-06-15 16:56:20,063] {subprocess.py:92} INFO - hey, I am task 3, and will be running after task 1 at the same time as task 2
[2022-06-15 16:56:20,065] {subprocess.py:96} INFO - Command exited with return code 0
[2022-06-15 16:56:20,121] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=third_task, execution_date=20220615T165617, start_date=20220615T165619, end_date=20220615T165620
[2022-06-15 16:56:20,183] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-15 16:56:20,233] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
